# Generated by Django 4.1.5 on 2023-02-08 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0006_alter_announcement_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-datetime'], 'verbose_name_plural': 'Announcement'},
        ),
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['-datetime'], 'verbose_name_plural': 'Assignment'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name_plural': 'Course'},
        ),
    ]
